### PR TITLE
Use on_stdout handler, removing indirection through tempfile

### PR DESCRIPTION
**Pull request by blueyed**
This allows to search for '<Enter' without adding it to the list of
escape characters for each tool.

### CODE REVIEW

**Comment by mhinz** [comment]
Hmm, what's the problem with `<Enter`?

Mind that [we used to do this in the past](https://github.com/mhinz/vim-grepper/commit/bb341c9ec63cf71655703013ed9e3372addeba9b), but it lead to a few terminal-related issues. E.g. the PR as-is doesn't work in my case (left master, right PR): http://imgur.com/CJRsr1r

This can be fixed by setting `pty: 0`, but this leads to another set of issues: https://github.com/mhinz/vim-grepper/issues/34

**Comment by blueyed** [comment]
The problem is that `<` and `>` get used as redirection in the shell command.
And I've liked that dropping the tempfile roundtrip causes the "Failed to read file" error to go away (but we could have a fileexists-check for that).

**Comment by mhinz** [comment]
Oh, right, it's up to the user to enter a valid command line. Same for escaping and quoting. But I agree that we need a better way to show error messages.

**Comment by blueyed** [comment]
Why would a user have to escape `>` and `<` (and other special characters)?

**Comment by mhinz** [comment]
I meant there are 2 ways to break the plugin:

- breaking the shell, as in your case (`git grep <foo` instead of `git grep '<foo'`)
- giving wrong input to the grep tool (`ag 'foo('` instead of `ag 'foo\('`)

**Comment by mhinz** [comment]
Hmm, since we depend on `sh` anyway, we could simply append a `| cat` to the command-line as well.

**Comment by mhinz** [comment]
Okay, I rebased and merged your commit with the usual small changes. :-)

(Now grepper runs smoother on Vim as well, since we don't go through `:grep` anymore but use `system()` directly. This also avoids the mean `set t_ti= t_te=` hack. Yay!)

Thanks!

**Pull request closed without merging**
