### PR TITLE
added windows support

### PR DESCRIPTION
**Pull request by prabirshrestha**
`:Grepper` using findstr. (default)

image

`:Grepper -tool git` using git

image

### CODE REVIEW

**Comment by mhinz** [comment]
Unfortunately I have no Windows to test this.

I see how this works in a pure Win environment (cmd.exe and powershell), but `has('win32')` also returns 1 if used with cygwin or the git shell etc. What happens if you use `cmd /c ...` there?

**Comment by mhinz** [comment]
The commit above should solve this problem.

@prabirshrestha Can you verify this?

**Comment by prabirshrestha** [comment]
@mhinz verified in gvim windows it works. Didn't try it in cygwin or git shell.

**Comment by mhinz** [comment]
Awesome, thanks for verifying and bringing it up!

**Pull request closed without merging**
