### PR TITLE
[RFC] Prompt: toggle --dir and --side on the fly

### PR DESCRIPTION
**Pull request by mhinz**
The Grepper prompt just learned about...

```
  <c-j>  Cycle through possible --dir options.
  <c-k>  Toggle --side.
```

References #167

### CODE REVIEW

**Comment by mhinz** [comment]
The PR lacks refactoring and documentation, but the functionality is there.

`<c-j>` and `<c-k>` are more or less randomly chosen. Better would be `<c-d>` and `<c-s>`, but these are often consumed by the terminal emulator (flow control) before Vim even sees it.

**Comment by lbonn** [comment]
Looks cool! Two notes:

- using `C-k` then `C-j` will just show the `[--dir xxx]`, but `--side` will still be active. Keeping `--side` is good, but one could argue that removing it from the prompt is confusing. On the other hand, it's quite easy to figure that out and it avoids making the prompt grow too big again.
- `C-j` and `C-k` are readline bindings, which can be useful for command mode (see https://github.com/tpope/vim-rsi). But I guess you intend to expose these bindings as user options, so this would not be really an issue. Also possible: `S-Tab` and `A-Tab`? (might be hard to remember which is which)

**Comment by mhinz** [comment]
> using C-k then C-j will just show the [--dir xxx], but --side will still be active. Keeping --side is good, but one could argue that removing it from the prompt is confusing. On the other hand, it's quite easy to figure that out and it avoids making the prompt grow too big again.

Yeah, adding it in front of the prompt was the best visualization I could come up with. The first version was slightly more complicated and showed `[--dir xxx, --side]` when `<c-k>` and `<c-j>` were pressed. But I think the current way works just as well, merely showing the result of the last shortcut. (And yes, it's shorter, too.) :)

> C-j and C-k are readline bindings, which can be useful for command mode (see https://github.com/tpope/vim-rsi). But I guess you intend to expose these bindings as user options, so this would not be really an issue. Also possible: S-Tab and A-Tab? (might be hard to remember which is which)

Usually I don't like introducing new options, but there doesn't seem to be a way around it.

The problem with with `<Tab> + modifier` is that many terminal emulators send the same key codes as `<Tab>` alone, so it can't distinguish between them. I chose `j` and `k` because they're easy to reach, but I don't like the fact that the characters are not very memorable, at least not for `dir` or `side`... Actually I can't come up with any choice that I like. Maybe we simply shouldn't map it by default and let the user decide?

Thinking about it, I'd prefer just mapping `<c-s>` and `<c-d>` by default and add a note to the doc about the potential problem in some terminals.

**Comment by mhinz** [comment]
Let's just roll with this and see if it works out, thanks for your input!

**Comment by stellarhoof** [comment]
I actually prefer `[--dir xxx, --side]`, but this way is fine as well.

**Comment by mhinz** [comment]
It might work for these 2 flags, but my reasoning was that it would be better to condition the users to the current way in case we ever need to add even more shortcuts for other flags. :>

**Pull request merged**
