### PR TITLE
Highlight: fix queries picked from the command window

### PR DESCRIPTION
**Pull request by glenvt18**
When selecting a query from the command window (Ctrl-f), s:prompt_op
should be set to 'cr', but there is no <cr> key event in this case.
So, do the opposite: catch Esc and Ctrl-c.

### CODE REVIEW

**Comment by mhinz** [comment]
After this commit, `<esc>` won't cancel the prompt anymore.

**Comment by glenvt18** [comment]
Updated.

**Comment by mhinz** [comment]
> When selecting a query from the command window 

Can you give a concrete example? I can't seem to see any differences.

**Comment by glenvt18** [comment]
Here you are.
```
vim ./grepper.vim
:Grepper
git> let
'let' is highlighted
:Grepper
git> endif
'endif' is highlited
:Grepper
git>
Ctrl-f and pick 'let'
now 'let' is not highlighted
```
This only happens when picking a query from the command window (Ctrl-f). Its because there is no '\<CR\> has been pressed' event in this case, but input() returns the selected query. In other words
\<CR\> mapping can't be used to detect that a query has been submitted. A not-empty input() result can be used for that, but it is used for a <cword> search.

**Comment by mhinz** [comment]
Does this work for you as well?

```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index cd1d418..859ec1d 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -768 +768 @@ function! s:prompt(flags)
-  let mapping_cr   = maparg('<cr>', 'c', '', 1)
+  let mapping_esc  = maparg('<esc>', 'c', '', 1)
@@ -774 +774 @@ function! s:prompt(flags)
-  cnoremap <cr> <end><c-\>e<sid>set_prompt_op('cr')<cr><cr>
+  cnoremap <esc> <c-\>e<sid>set_prompt_op('cancelled')<cr><c-c>
@@ -801 +801 @@ function! s:prompt(flags)
-  let s:prompt_op = 'cancelled'
+  let s:prompt_op = 'cr'
@@ -813 +813 @@ function! s:prompt(flags)
-    cunmap <cr>
+    cunmap <esc>
@@ -817 +817 @@ function! s:prompt(flags)
-    call s:restore_mapping(mapping_cr)
+    call s:restore_mapping(mapping_esc)
```

Note that the `<esc>` mapping does `<c-c>` at the end now.

**Comment by glenvt18** [comment]
Yes, this trick works fine. But I don't like the idea of Ctrl-c interrupt ever leaving this function. If we catch it, we also have to clear a:flags.query to signal that the search is to be aborted. Maybe s:prompt should return a boolean for clariry. Running a \<cword\> search on an empty query is handy (less shortcuts to memorize), but it's not obvious without looking at the code))

**Comment by mhinz** [comment]
Yea, the whole prompt code is a complete mess and could use some refactoring. The `empty input -> cword` thing was an early requested feature and is documented at `:h grepper-intro`.

Anyway, can you change this PR to the following diff:

```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index cd1d418..c4f0b91 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -768 +768 @@ function! s:prompt(flags)
-  let mapping_cr   = maparg('<cr>', 'c', '', 1)
+  let mapping_esc  = maparg('<esc>', 'c', '', 1)
@@ -774 +774 @@ function! s:prompt(flags)
-  cnoremap <cr> <end><c-\>e<sid>set_prompt_op('cr')<cr><cr>
+  cnoremap <esc> <c-\>e<sid>set_prompt_op('cancelled')<cr><c-c>
@@ -801 +801 @@ function! s:prompt(flags)
-  let s:prompt_op = 'cancelled'
+  let s:prompt_op = 'cr'
@@ -808,0 +809,2 @@ function! s:prompt(flags)
+  catch /^Vim:Interrupt$/
+    let s:prompt_op = 'cancelled'
@@ -813 +815 @@ function! s:prompt(flags)
-    cunmap <cr>
+    cunmap <esc>
@@ -817 +819 @@ function! s:prompt(flags)
-    call s:restore_mapping(mapping_cr)
+    call s:restore_mapping(mapping_esc)
```

This should be fine now, I guess?

**Comment by glenvt18** [comment]
Yes, it works. I'll update this PR.
> Do we? Seems to work fine without it.

Well, it was late at night... Yet another trick: Ctrl-c clears the string returned by set_prompt_op ))
Maybe it's better to express it explicitly, something like
`return a:op == 'cancelled' ? '' : getcmdline()` in set_prompt_op (and not use \<c-c\>)?
\<c-c\> also doesn't throw an interrupt. So we catch only 'true' Ctrl-c interrupts. Hope neovim behaves the same way.

> Same as what?

As it was before - without \<c-c\>. It's still slow. I now nothing about those timeouts, don't ask me.

I'm preparing an updated PR...

**Comment by mhinz** [comment]
> Well, it was late at night...

:)

> <c-c> also doesn't throw an interrupt. So we catch only 'true' Ctrl-c interrupts.

Yup, it's the difference between `:h ctrl-c` and `:h c_ctrl-c`. Both is covered in the latest diff.

In a follow-up commit we can silence the mappings to avoid the flashing of `set_prompt_op('cancelled')` for a blink of an eye.

> As it was before - without <c-c>. It's still slow. I now nothing about those timeouts, don't ask me.

When you have ambiguous mappings, Vim has to wait for further key presses to know which mapping is meant exactly. `<esc>` is a special case since a lot of _escape_ sequences in terminal emulators start with, well, `<esc>`.

That's why we temporarily set the timeout to 100 msec ([here](https://github.com/mhinz/vim-grepper/blob/539f5e7fbd021a66e57b5ca2ae78ca1f2e7af360/plugin/grepper.vim#L782-L783)) before calling `input()` and restore it afterwards. If it's noticeably slower for you, we should figure out a solution in another issue.

**Comment by glenvt18** [comment]
Thanks for the explainations.

> If it's noticeably slower for you, we should figure out a solution in another issue.
 
It certainly looks more as 1 sec than 100 msec.

The commit has been updated.

**Comment by mhinz** [comment]
> The commit has been updated.

Thanks!

> It certainly looks more as 1 sec than 100 msec.

Is `:map <esc>` showing any mappings? Does it help to do `:set timeout timeoutlen=400`? (This applies to all mappings and is just for testing purposes.)

**Comment by glenvt18** [comment]
> Is :map <esc> showing any mappings?

Yes. I'm running GNU screen and there are `<Esc>[200~` mappings for the bracketed paste support. If I run vim in a pure xterm (without screen), Esc is fast. Setting timeouts in a screen session does take effect, but it's rather small.

BTW. I added whitespace removal to the original commit mostly to suppress nusty errors when submitting a line containing whitespace only. It was right after s:prompt return and before the empty() check which triggers cword search. Is it a wrong place?

**Comment by mhinz** [comment]
> I added whitespace removal to the original commit mostly to suppress nasty errors when submitting a line containing whitespace only.

Put such things into separate commits and describe in the commit message why they are needed. :)

> I'm running GNU screen and there are <Esc>[200~ mappings for the bracketed paste support. If I run vim in a pure xterm (without screen), Esc is fast. Setting timeouts in a screen session does take effect, but it's rather small.

It's been ages since I last used screen, but when using such "middleware" between terminal emulator and application, it needs to adjust its timeouts as well. Does putting `maptimeout 5` in your `.screenrc` help?

**Comment by glenvt18** [comment]
> Put such things into separate commits and describe in the commit message why they are needed. :)

Looks like you've already done that. Thanks.

>  Does putting maptimeout 5 in your .screenrc help?

No.

**Comment by mhinz** [comment]
Did you try it together with `:set timeout timeoutlen=300`? Otherwise there's nothing else I can do from the plugin side.

**Comment by glenvt18** [comment]
`:set timeout timeoutlen=300` works but shortcuts feel a bit awkward.

**Pull request merged**
