### PR TITLE
Fix missing 'cwd' handler for -dir flag

### PR DESCRIPTION
**Pull request by grwlf**

### CODE REVIEW

**Comment by mhinz** [comment]
Can you give an example that isn't working without this patch?

**Comment by grwlf** [comment]
I am using the following function to run the Grepper from NERDTree node `node`
```
    function! _run_grepper_nerd(node)
      let oldcwd = getcwd()
      let newcwd = a:node.path.getDir().str()
      exec "wincmd w"
      exec "cd " . fnameescape(newcwd)
      exec "Grepper -noqf -prompt"
      exec "cd " . fnameescape(oldcwd)
    endfunction
```

Without this patch, long-running grep processes running from `./subdir` will add their results while vim is in `oldcwd` dir (typically a project root).

An alternative solution could be adding `-cd <dir>` flag to Grepper. I was surprised to see it is absent.

**Comment by mhinz** [comment]
Thanks! ✨

> One alternative solution I see - is to add `-cd <dir>` flag to Grepper. I was surprised to know its missing

My thinking was that no one would type in the path as an argument to `-cd`, when they could just `:cd` there first having proper tab-completion et al. And for scripting purposes using `:cd` around `:Grepper` would be easy enough.

But then again, it would be so easy to implement, we might as well just do it.

**Comment by mhinz** [comment]
For `-cd`, follow https://github.com/mhinz/vim-grepper/issues/208.

**Pull request merged**
